### ISSUE TITLE
init too much list items on the infinite mode

### ISSUE THREAD

**Issue by sinchang** [brainhubeu/react-carousel#497] opened 2020-05-21 07:07 UTC
**Describe the bug**
if we have 3 items originally will clone 18 items on the infinite mode

**To Reproduce**
go to https://codesandbox.io/s/still-architecture-j2e9m

open console and run `document.querySelectorAll('.BrainhubCarouselItem')`

**Expected behavior**
reduce the number of initial list items

**Screenshots**

**Environment**
- please paste the result of `npx envinfo --system --binaries --browsers --npmPackages '@brainhubeu/*'`
- desktop or mobile (which device & OS if mobile)?
- Browser [e.g. Chrome, Safari]

**Additional context**
Finally. I found that we have the config `numberOfInfiniteClones` (current is 3) to control the number of clones.

**Comment by piotr-s-brainhub** [comment] 2020-05-21 10:18
@sinchang 

Thanks for reporting this.

I reproduced that. It happens also in the docs/ demo. It's strange that there are so many slides even before switching slides and it's contrary to the `numberOfInfiniteClones`.

You're welcome to open a PR.

You can also invite your colleagues to like (👍) this issue, so more 👍it has, it's more likely to be fixed by us.

**Comment by piotr-s-brainhub** [comment] 2020-05-21 10:19
<img width="1305" alt="Screenshot 2020-05-21 at 12 16 40" src="https://user-images.githubusercontent.com/20856232/82549427-357efd00-9b5d-11ea-9548-f2552770c11c.png">

**Comment by sinchang** [comment] 2020-05-22 05:37
@Lukasz-pluszczewski can we modify the `numberOfInfiniteClones ` to `1`

**Comment by Lukasz-pluszczewski** [comment] 2020-05-22 12:14
The reason it has been set to 3 is to allow controlled carousel to show smooth animation when changing the slide index by a large number (e.g. if you have 3 slides, and want to animate infinite carousel moving by 10 slides to the right)

It may have a significant performance impact especially on mobile, so I'm ok with changing the default value to 1, but keeping in mind the above, I would maybe add it as optional parameter.

**Comment by R1cro** [comment] 2020-07-07 11:52
@piotr-s-brainhub @Lukasz-pluszczewski is there any way to change `numberOfInfiniteClones` to 1 through props?

I would be grateful if you would suggest how this can be regulated.

Thank you.

**Comment by piotr-s-brainhub** [comment] 2020-07-07 12:14
@R1cro 

Currently, it's not possible because it's hardcoded in the config but a simple PR should be able to change this.

**Comment by RobertHebel** [comment] 2020-07-21 20:13
@R1cro it's possible in carousel v2 (currently in beta). More details here https://brainhubeu.github.io/react-carousel/docs/plugins/plugins#infinite-plugin

**Closed by RobertHebel** 2020-07-21 20:13 UTC
Labels: answering: not answered, severity: minor, type: bug

**Comment by jefferymills** [comment] 2020-07-22 18:28
> @R1cro
> 
> Currently, it's not possible because it's hardcoded in the config but a simple PR should be able to change this.

Would a PR making this changeable through props get accepted for release before 2.0? We currently experience crashes on some IOS devices and in our case we don't need that many clones. I would be happy to add it if it would get merged. If not then we can work around it until 2.0 is released.
