### ISSUE TITLE
Touch event causes page crash

### ISSUE THREAD

**Issue by martinpetts** [brainhubeu/react-carousel#147] opened 2019-10-04 16:35 UTC
When attempting to scroll a carousel using touch on mobile, it breaks the carousel and causes an error. This is visible on the demo site: https://brainhubeu.github.io/react-carousel/docs/examples/responsive/

See screenshot:
![Screenshot 2019-10-04 at 18 31 32](https://user-images.githubusercontent.com/184933/66224183-8ed11380-e6d5-11e9-88fa-eeb2c486d671.png)

Tested on Chrome Mac, Chrome Android (Pixel 3) and Safari iOS (iPad).

**Comment by piotr-s-brainhub** [comment] 2019-10-04 21:34
Thanks @martinpetts 

could you provide the following?
- `react-carousel` version
- Chrome version (both Mac and Android)
- Mac version
- Android version
- iOS version

**Comment by martinpetts** [comment] 2019-10-04 22:16
Hi
react-carousel: I'm using 1.10.24, don't know what version your demo is
using
Chrome Mac: 77.0.3865.90
Mac OS: 10.14.6
Android: 10 (5 Sep 2019)
iPad OS: 13.1.1

**Comment by filfat** [comment] 2019-10-08 09:04
Happens on `1.10.24` here too!

**Comment by ernestognw** [comment] 2019-10-09 07:00
Hey guys,

I've checked the issue since I had the problem too.

It was caused by a refactor in https://github.com/brainhubeu/react-carousel/commit/1dbfb207127fafe1e455d708ef2db932d097f054 in which the setState methods were updated without pooling the events that were used for the drag property.

I'll be taking care of this, so I'm gonna send u a PR in a few minutes

**Comment by pierzchalatomasz** [comment] 2020-01-02 13:20
Closing, since it's fixed

**Closed by pierzchalatomasz** 2020-01-02 13:20 UTC
Labels: hacktoberfest, needs testing

**Comment by piotr-s-brainhub** [comment] 2020-02-07 21:30
@martinpetts @filfat @ernestognw 

Can I ask you to fill in this form https://docs.google.com/forms/d/1tfRs1Io49tJBwz-06aDnz8hrJ3WySJTi45y4k6hHGaQ ?
