### ISSUE TITLE
Chrome Update version 80 causes wrong calculation of Carousel track width on resizing

### ISSUE THREAD

**Issue by alicemao23** [brainhubeu/react-carousel#251] opened 2020-02-10 16:35 UTC
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%240%20Funded-%2300A156.svg" />](https://issuehunt.io/r/brainhubeu/react-carousel/issues/251)

**Describe the bug**
Update to Chrome version 80.0 is creating error calculation on the window object's innerWidth value. Using mobile tools on different device size, and logging window.innerWidth renders 1500px for device width viewPort of 375, etc. Continuous resizing will compound the size of the window's innerWidth. This behaviour is not replicated in other browsers (tested on safari & firefox atm) 

**To Reproduce**
1. Update chrome browser to version 80 
2. Run a page with the carousel displayed on the DOM
3. Open the inspector tool to log window.innerWidth

**Expected behavior**
window.innerWidth should be showing the same px as the px size of the viewPort 

**Screenshots**
![Screen Shot 2020-02-10 at 11 32 55 AM](https://user-images.githubusercontent.com/16654190/74169408-441e5580-4bf9-11ea-98d6-e1621978838d.png)

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser: Chrome
 - Version 80.0.3987.87

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/brainhubeu/react-carousel/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by piotr-s-brainhub** [comment] 2020-02-10 16:45
Thanks @alicemao23 for reporting.
So what's the latest Chrome version where it was working correctly?
Do you use the latest `@brainhubeu/react-carousel` version?

**Comment by sergueyarellano** [comment] 2020-02-10 17:19
Yeah I have the same issue with chrome 80.

**Comment by alicemao23** [comment] 2020-02-10 17:31
@piotr-s-brainhub I just updated the package version to latest, and the bug still persists. The latest version that the package was working correctly was version 79.

**Comment by piotr-s-brainhub** [comment] 2020-02-19 17:08
I checked this bug occurs in Chrome 82.0.4062.3 (canary) as well.

**Comment by piotr-s-brainhub** [comment] 2020-02-19 21:12
@alicemao23 @sergueyarellano 

can't you use `window.outerWidth` and `window.outerHeight` instead?
<img width="968" alt="Screenshot 2020-02-19 at 21 58 08" src="https://user-images.githubusercontent.com/20856232/74875710-004aef00-5363-11ea-8eb1-7d11b2ccb06a.png">

**Comment by alicemao23** [comment] 2020-02-24 14:53
@piotr-s-brainhub sorry I was away from internet for a few days. This is causing an issue because the react carousel repo itself is using window.innerWidth to set the width of the track - I was going through the code and saw that it may be used in the `onResize` function. Because of this, the track is being calculated wrong, and is stretching the carousel to be much wider than the screen width, hence breaking the UI when we're using it. We're not really using window.innerWidth, the react-carousel repo is.

**Comment by piotr-s-brainhub** [comment] 2020-02-24 15:04
thanks @alicemao23 

I used `outerWidth ` in in https://github.com/brainhubeu/react-carousel/pull/288 so I'm going to compare the behavior on `master` and that branch.

**Comment by piotr-s-brainhub** [comment] 2020-05-13 23:57
@sergueyarellano 

Instead of writing a comment, I invite you to like this issue (👍) so we could sort the issues by the number of 👍and more 👍a given issue has, more likely it's to be fixed.

**Comment by piotr-s-brainhub** [comment] 2020-05-28 00:36
@alicemao23 @sergueyarellano 

Do you still encounter this issue?

Recently we fixed some other similar issues so there's a chance this is already fixed.

**Comment by RobertHebel** [comment] 2020-07-21 19:08
Closing as I can't reproduce this issue anymore. Please reopen if you'll manage to reproduce it

**Closed by RobertHebel** 2020-07-21 19:08 UTC
Labels: answering: not answered, severity: medium, type: bug

**Comment by alexjfno1** [comment] 2020-10-29 11:20
I'm still getting this issue, i'm on Chrome 86. The only way I found to fix it was to have a fixed size div around the Carousel with `width: 100vw` as using `100%` didn't work. Is there a solution to this issue?
