### ISSUE TITLE
fade

### ISSUE THREAD

**Issue by piotr-s-brainhub** [brainhubeu/react-carousel#483] opened 2020-05-13 18:56 UTC
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%240%20Funded-%2300A156.svg" />](https://issuehunt.io/r/brainhubeu/react-carousel/issues/483)

When `onChangingSlide: 'fade'` passed to the Carousel, it should fade when changing slides like in https://react-slick.neostack.com/docs/example/fade

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/brainhubeu/react-carousel/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by yashrajjain726** [comment] 2020-05-27 13:15
Can you please specify the location of the code.

**Comment by piotr-s-brainhub** [comment] 2020-05-27 13:49
@yashrajjain726 

here https://github.com/brainhubeu/react-carousel/blob/master/src/components/Carousel.js is the Carousel component

**Comment by yashrajjain726** [comment] 2020-05-27 15:00
But you don't have an option of 'fade' in your code as you shown in the example
https://react-slick.neostack.com/docs/example/fade
In which example you want to add the property fade ?
![Capture](https://user-images.githubusercontent.com/53373012/83036954-d2a7cd00-a058-11ea-9a16-d96dd537d7e7.JPG)

**Comment by piotr-s-brainhub** [comment] 2020-05-27 15:02
@yashrajjain726 

There should be a new example for that.

**Comment by piotr-s-brainhub** [comment] 2020-06-12 14:17
@rohitgupta200305 

I see you've requested a bounty of 40 USD for fixing this issue on IssueHunt. Would 20 USD work for you so there would be 22 USD for fixing this issue (2 + 20) minus the IssueHunt fee?

**Comment by RobertHebel** [comment] 2020-07-21 20:04
Duplicate of https://github.com/brainhubeu/react-carousel/issues/323

**Closed by RobertHebel** 2020-07-21 20:04 UTC
Labels: answering: not answered, type: enhancement
