### ISSUE TITLE
Touch events make buttons unresponsive on Chrome

### ISSUE THREAD

**Issue by micabe** [brainhubeu/react-carousel#70] opened 2018-11-06 13:04 UTC
[Intervention] Ignored attempt to cancel a touchend event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.

**Comment by micabe** [comment] 2018-11-06 16:33
Hey @mdrazyk 
Basically steps to reproduce are:
1) go on Chrome
2) turn on mobile device view
3) try to swipe on the carousel, it fails

> TLDR the lib is not working on any mobile devices that have touch enabled

**Comment by orangecms** [comment] 2018-11-06 21:44
This looks like a duplicate of #47 which I created a fixup for :)

**Comment by micabe** [comment] 2018-11-07 09:10
@orangecms brillant!
thanks for the fix
Waiting for your pull request dude 👍

**Comment by adam-golab** [comment] 2018-11-15 08:51
The Pull Request is already merged. Please let us know if the issue is still present.

**Closed** 2019-06-11 21:19 UTC

**Comment by piotr-s-brainhub** [comment] 2020-02-07 21:33
@micabe @orangecms 

Can I ask you to fill in this form https://docs.google.com/forms/d/1tfRs1Io49tJBwz-06aDnz8hrJ3WySJTi45y4k6hHGaQ ?
