### ISSUE TITLE
Dots doesn't respect number prop when used for thumbnails

### ISSUE THREAD

**Issue by andycarrell** [brainhubeu/react-carousel#109] opened 2019-06-13 22:44 UTC
**Describe the bug**
Number prop not respected on 'Dots' when thumbnails prop is supplied.

**To Reproduce**
1. Go to https://brainhubeu.github.io/react-carousel/docs/examples/thumbnails
2. Click on change live example prop for Dots from `this.state.thumbnails.length` to "2" 
3. Check thumbnails

**Expected behavior**
There should only be two thumbnails showing

**Screenshots**
![Screen Shot 2019-06-14 at 10 43 19 AM](https://user-images.githubusercontent.com/22784983/59472443-92c0f780-8e92-11e9-98ae-dfe1a4dd50de.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser All
 - Version All

**Comment by piotr-s-brainhub** [comment] 2019-06-19 10:52
Thanks for reporting this.
Unfortunately we don't have enough time to resolve this issue.
Anyway a PR is more than welcome.

**Comment by udaypydi** [comment] 2019-09-30 16:05
Hi, 
I have submitted a PR for this issue. Please check.

PR: https://github.com/brainhubeu/react-carousel/pull/124

Thanks

**Comment by piotr-s-brainhub** [comment] 2019-09-30 16:18
thanks @udaypydi

**Comment by udaypydi** [comment] 2019-09-30 16:24
I have updated the PR as per your review.
Thanks

**Comment by pierzchalatomasz** [comment] 2020-01-03 14:52
Closing - the issue is already fixed

**Closed by pierzchalatomasz** 2020-01-03 14:52 UTC
Labels: hacktoberfest, needs testing

**Comment by piotr-s-brainhub** [comment] 2020-02-07 21:31
@andycarrell 

Can I ask you to fill in this form https://docs.google.com/forms/d/1tfRs1Io49tJBwz-06aDnz8hrJ3WySJTi45y4k6hHGaQ ?

**Comment by andycarrell** [comment] 2020-02-10 01:24
Hi @piotr-s-brainhub - sorry I don't really feel comfortable giving out my email on your form 👐
Quick feedback would be a more rapid response to issues would be appreciated :)

**Comment by piotr-s-brainhub** [comment] 2020-02-10 14:58
thanks @andycarrell , you can possibly use a fake email but the comment above is appreciated as well
