### ISSUE TITLE
major bug: library leaks something globally and destroys react-select

### ISSUE THREAD

**Issue by liranreg** [brainhubeu/react-carousel#114] opened 2019-07-25 12:25 UTC
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2450%20Funded-%2300A156.svg" />](https://issuehunt.io/r/brainhubeu/react-carousel/issues/114)

Hello,
I started using react-carousel a week ago.. and suddenly we realized our all application is broken.
React-Select, one of the most popular libraries, is getting broken.

Just adding the bare tag ```<Carousel/>``` to the page, makes react-select components to not be able to open. they get opened and closed immediately.

removing the tag resolves it.

I don't know why this is happening, but it does.. and I think its a huge bug as it means a lot o website will be broken when start using react-carousel.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $50.00)

- [<img src='https://avatars0.githubusercontent.com/u/20856232?v=4' alt='piotr-s-brainhub' width=24 height=24> piotr-s-brainhub](https://issuehunt.io/u/piotr-s-brainhub) ($50.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/brainhubeu/react-carousel/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by piotr-s-brainhub** [comment] 2019-07-25 15:43
Hi @liranreg 

Thanks for reporting that.

Could you provide more info:
- Which browser do you use and which version?
- Which OS do you use and which version?
- Could you publish a simple example project with this bug (as a new repo with sending a link here)?

Anyway we have very limited resources now so I cannot guarantee we'll be able to fix that. So it will be more than welcome if you open a PR with fix.

**Comment by LiranBri** [comment] 2019-07-25 16:39
Hi,it's happening only on mobile. Both on iPhone and android.
It also happens on chrome dev tools with mobile emulator

My mobile chrome version is 75.03 and I have Samsung s10 pro

**Comment by liranreg** [comment] 2019-07-26 06:05
Hi, it's happening only on mobile. Both on iPhone and android.
It also happens on chrome dev tools with mobile emulator

My mobile chrome version is 75.03 and I have Samsung s10 pro.

regarding PR with a fix. i'll be glad to do that. but I just need you to help me understand whats the source of the bug, because I couldn't find it.

**Comment by dongreenmedl** [comment] 2019-08-09 01:31
Hi there, I believe this bug lies deeper than react-select and actually somehow affects `<select>` inputs in general. What I have found on a site I have implemented this package on, is that now the `<select>` dropdown inputs will trigger to open and focus (on mobile devices) on mousedown instead of on mouseup. This has serious implications on mobile (especially iOS since iOS likes to scroll the view to center on the focused input). The side effect I am experiencing is unwanted touch events on other elements due to the focus scrolling effect causing other mouseup events to fire in the offset position based on the amount of scroll.

I believe there is something about the registration of the event listeners in this package that is somehow targeting other elements outside of the target elements this package should be responsible for.

**Comment by nik72619c** [comment] 2019-10-03 19:05
can I work on this ?

**Comment by piotr-s-brainhub** [comment] 2019-10-03 21:39
@nik72619c 

sure, you're welcome to open a PR

**Comment by piotr-s-brainhub** [comment] 2020-01-21 23:54
@dongreenmedl 

I see your example works on iPhone in the same way, no matter whether `@brainhubeu/react-carousel` is imported or not.

**Comment by piotr-s-brainhub** [comment] 2020-02-07 21:24
@liranreg @dongreenmedl @nik72619c @jamsinclair 

Can I ask you to fill in this form https://docs.google.com/forms/d/1tfRs1Io49tJBwz-06aDnz8hrJ3WySJTi45y4k6hHGaQ ?

**Comment by piotr-s-brainhub** [comment] 2020-02-12 13:56
@liranreg @dongreenmedl 

do you still encounter this issue?

**Comment by piotr-s-brainhub** [comment] 2020-02-19 21:20
@liranreg @dongreenmedl 

As there's no reply and I cannot reproduce, I close this issue.

**Closed by piotr-s-brainhub** 2020-02-19 21:20 UTC
Labels: :dollar: Funded on Issuehunt, bug
