### ISSUE TITLE
High version threw error; 1.16.3 version is running

### ISSUE THREAD

**Issue by codeWebZhang** [brainhubeu/react-carousel#569] opened 2020-06-25 03:19 UTC
**Describe the bug**

**To Reproduce**
1. use 1.16.3 is running, when upgraded version is error;
2.
![image](https://user-images.githubusercontent.com/44563963/85649544-fbfa5e00-b6d5-11ea-85ec-54879efd677f.png)

3. I hope to get help  thank you

**Comment by piotr-s-brainhub** [comment] 2020-06-25 12:06
@codeWebZhang 

Thanks for reporting this but it's a duplicate of the https://github.com/brainhubeu/react-carousel/issues/549 so I invite you to like (👍) the original issue.

**Closed** 2020-06-25 13:15 UTC
Labels: answering: answered

**Comment by codeWebZhang** [comment] 2020-06-26 02:21
> @codeWebZhang
> 
> Thanks for reporting this but it's a duplicate of the #549 so I invite you to like (👍) the original issue.

ok
